#include <tdc/vec/fixed_width_int_vector.hpp>

using namespace tdc::vec;

template class FixedWidthIntVector<2>;
template class FixedWidthIntVector<3>;
template class FixedWidthIntVector<4>;
template class FixedWidthIntVector<5>;
template class FixedWidthIntVector<6>;
template class FixedWidthIntVector<7>;
template class FixedWidthIntVector<8>;
template class FixedWidthIntVector<9>;
template class FixedWidthIntVector<10>;
template class FixedWidthIntVector<11>;
template class FixedWidthIntVector<12>;
template class FixedWidthIntVector<13>;
template class FixedWidthIntVector<14>;
template class FixedWidthIntVector<15>;
template class FixedWidthIntVector<16>;
template class FixedWidthIntVector<17>;
template class FixedWidthIntVector<18>;
template class FixedWidthIntVector<19>;
template class FixedWidthIntVector<20>;
template class FixedWidthIntVector<21>;
template class FixedWidthIntVector<22>;
template class FixedWidthIntVector<23>;
template class FixedWidthIntVector<24>;
template class FixedWidthIntVector<25>;
template class FixedWidthIntVector<26>;
template class FixedWidthIntVector<27>;
template class FixedWidthIntVector<28>;
template class FixedWidthIntVector<29>;
template class FixedWidthIntVector<30>;
template class FixedWidthIntVector<31>;
template class FixedWidthIntVector<32>;
template class FixedWidthIntVector<40>;
template class FixedWidthIntVector<48>;
template class FixedWidthIntVector<56>;
template class FixedWidthIntVector<64>;
